Added SIGIL configuration

diff --git a/install b/install
--- a/install
+++ b/install
@@ -37,7 +37,26 @@ function install-brutal-doom () {
     then
         printf "\nDone.\n"
     else
-        printf "\nCould not install!\n"
+        printf "\nCould not install Brutal Doom!\n"
+        return $RET
+    fi
+
+    return $RET
+}
+
+function install-sigil () {
+    cd sigil
+    ./install
+
+    RET=$?
+
+    cd .. 
+
+    if [ $RET -eq 0 ]
+    then
+        printf "\nDone.\n"
+    else
+        printf "\nCould not install SIGIL!\n"
         return $RET
     fi
 
@@ -55,6 +74,9 @@ then
     elif [ $ARG = gzdoom ]
     then
         install-gzdoom
+    elif [ $ARG = sigil ]
+    then 
+        install-sigil
     else
         printf "\nInvalid argument '%s'\n" $ARG 
         exit 1
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -23,7 +23,7 @@ function uninstall-brutal-doom () {
     printf "Installing Brutal Doom ... \n\n"
 
     cd brutal
-    ./remove
+    ./uninstall
         
     RET=$?
 
@@ -40,6 +40,27 @@ function uninstall-brutal-doom () {
     return $RET
 }
 
+function uninstall-brutal-doom () {
+    printf "Installing SIGIL ... \n\n"
+
+    cd sigil
+    ./uninstall
+        
+    RET=$?
+
+    cd ..
+
+    if [ $RET -eq 0 ]
+    then
+        printf "\nDone.\n"
+    else
+        printf "\nCould not remove SIGIL!\n"
+        return $RET
+    fi
+
+    return $RET
+}
+
 
 if [ $# -eq 2 ]
 then
@@ -50,6 +71,9 @@ then
     elif [ $ARG = gzdoom ]
     then
         uninstall-gzdoom
+    elif [ $ARG = sigil ]
+    then 
+        uninstall-sigil
     else
         printf "Invalid argument '%s'\n" $ARG 
         exit 1
